import { type ReactNode, createContext, useContext, useState } from "react";

export type Lang = "en" | "hi";

const translations = {
  en: {
    appName: "Digital Evidence Protection System",
    appShort: "DEPS",
    home: "Home",
    about: "About System",
    upload: "Evidence Upload",
    verify: "Verify Evidence",
    dashboard: "Case Dashboard",
    admin: "Admin Panel",
    contact: "Contact",
    login: "Login",
    logout: "Logout",
    signup: "Sign Up",
    uploadEvidence: "Upload Evidence",
    verifyEvidence: "Verify Evidence",
    evidenceId: "Evidence ID",
    sha256Hash: "SHA-256 Hash",
    tamperDetected: "Tamper Detected",
    evidenceVerified: "Evidence Verified",
    uploadFile: "Upload File",
    createCase: "Create Case",
    activityLog: "Activity Log",
    caseId: "Case ID",
    status: "Status",
    description: "Description",
    fileName: "File Name",
    fileSize: "File Size",
    fileType: "File Type",
    timestamp: "Timestamp",
    uploadedBy: "Uploaded By",
    sealCase: "Seal Case",
    assignEvidence: "Assign Evidence",
    noTampering: "Evidence Verified — No Tampering Detected",
    tamperAlert: "Tamper Detected — Hash Mismatch",
    heroSubtitle:
      "Securing digital evidence with cryptographic integrity for law enforcement, forensic teams, and judicial authorities.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    secureStorage: "Tamper-Proof Storage",
    hashIntegrity: "SHA-256 Integrity",
    roleAccess: "Role-Based Access",
    chainCustody: "Chain of Custody",
    realTimeVerify: "Real-Time Verification",
    multiAgency: "Multi-Agency Support",
    evidenceSecured: "Evidence Secured",
    casesSolved: "Cases Solved",
    agencies: "Agencies",
    uptime: "Uptime",
    name: "Name",
    email: "Email",
    message: "Message",
    send: "Send Message",
    department: "Department",
    badgeNumber: "Badge Number",
    role: "Role",
    displayName: "Display Name",
    password: "Password",
    allCases: "All Cases",
    openCases: "Open Cases",
    totalEvidence: "Total Evidence",
    recentActivity: "Recent Activity",
    users: "Users",
    cases: "Cases",
    evidence: "Evidence",
    logs: "Logs",
    officers: "Officers",
    investigators: "Investigators",
    admins: "Admins",
    howItWorks: "How It Works",
    step1: "Upload Evidence",
    step1Desc: "Securely upload digital files with metadata and case details.",
    step2: "Hash & Record",
    step2Desc:
      "SHA-256 hash is computed and immutably stored on the blockchain.",
    step3: "Verify Integrity",
    step3Desc: "Compare hashes anytime to detect tampering or corruption.",
    // About page
    aboutTagline: "About System",
    aboutHeroTitle: "Protecting",
    aboutHeroTitleHighlight: "Digital Truth",
    aboutHeroDesc:
      "DEPS is a next-generation forensic evidence management platform built on cryptographic principles and decentralized infrastructure. Our mission: ensure every piece of digital evidence remains authentic, verifiable, and legally admissible.",
    ourMission: "Our",
    ourMissionHighlight: "Mission",
    missionDesc1:
      "In an era where digital evidence is central to justice, tampering and manipulation pose existential threats to legal proceedings. DEPS was created to solve this problem definitively.",
    missionDesc2:
      "By combining SHA-256 cryptographic hashing with blockchain immutability, we create a system where evidence integrity can be mathematically proven — not just claimed.",
    systemStats: "SYSTEM STATISTICS",
    statEvidenceRecords: "Total Evidence Records",
    statHashVerifications: "Hash Verifications Performed",
    statTamperAttempts: "Tamper Attempts Detected",
    statActiveAgencies: "Active Agencies",
    statSystemUptime: "System Uptime",
    techStack: "Technology",
    techStackHighlight: "Stack",
    whoUses: "Who Uses",
    techIcpTitle: "ICP Blockchain",
    techIcpDesc:
      "Evidence metadata and hashes stored permanently on the Internet Computer Protocol — a decentralized, tamper-proof blockchain platform.",
    techShaTitle: "SHA-256 Cryptographic Hashing",
    techShaDesc:
      "Industry-standard one-way hash function generates a unique 256-bit fingerprint for every file. Any byte-level change produces a completely different hash.",
    techRbacTitle: "Role-Based Access Control",
    techRbacDesc:
      "Three-tier permission system (Admin, Investigator, Officer) ensures that only authorized personnel can upload, view, or manage evidence.",
    techStorageTitle: "Decentralized Storage",
    techStorageDesc:
      "Files are stored in a distributed manner using ExternalBlob references — no single point of failure or censorship.",
    useLawTitle: "Law Enforcement",
    useLawDesc:
      "Police agencies can upload crime scene digital evidence with automatic chain-of-custody logging, ensuring admissibility in court.",
    useForensicsTitle: "Cyber Forensics",
    useForensicsDesc:
      "Forensic analysts can preserve disk images, memory dumps, and network captures with cryptographic integrity guarantees.",
    useJudiciaryTitle: "Judiciary",
    useJudiciaryDesc:
      "Courts can independently verify evidence integrity before proceedings using the public verification module.",
    // Scam types
    scamType: "Scam Type",
    selectScamType: "Select Scam Type",
    phishing: "Phishing Attack",
    financialFraud: "Financial Fraud",
    identityTheft: "Identity Theft",
    shoppingScam: "Online Shopping Scam",
    investmentScam: "Investment Scam",
    jobFraud: "Job Fraud",
    lotteryScam: "Lottery / Prize Scam",
    romanceScam: "Romance Scam",
    cyberBullying: "Cyber Bullying",
    ransomware: "Ransomware / Malware",
    // Role Portal
    myPortal: "My Portal",
    selectRole: "Select Your Role",
    selectRoleDesc: "Choose your role to access your personalized dashboard",
    investigatorRole: "Investigator",
    investigatorRoleDesc:
      "Access case files, evidence review, and chain of custody",
    officerRole: "Field Officer",
    officerRoleDesc: "Submit evidence, manage assignments, and field notes",
    citizenRole: "Citizen",
    citizenRoleDesc: "File complaints, track cases, and verify evidence",
    enterDashboard: "Enter Dashboard",
    // Investigator Dashboard
    investigatorPortal: "INVESTIGATOR PORTAL",
    restrictedAccess: "RESTRICTED ACCESS",
    activeCases: "Active Cases",
    evidenceItems: "Evidence Items",
    pendingReview: "Pending Review",
    chainEntries: "Chain Entries",
    caseFiles: "Case Files",
    evidenceReview: "Evidence Review",
    chainOfCustody: "Chain of Custody",
    analytics: "Analytics",
    searchCases: "Search cases...",
    searchEvidence: "Search evidence...",
    caseIdLabel: "Case ID",
    priorityLabel: "Priority",
    evidenceCount: "Evidence count",
    high: "HIGH",
    medium: "MEDIUM",
    low: "LOW",
    verified: "VERIFIED",
    pending: "PENDING",
    active: "ACTIVE",
    closed: "CLOSED",
    open: "OPEN",
    // Officer Dashboard
    officerFieldPortal: "OFFICER FIELD PORTAL",
    fieldAccess: "FIELD ACCESS",
    activeDuty: "ACTIVE DUTY",
    mySubmissions: "My Submissions",
    assignedCases: "Assigned Cases",
    pendingReviewStat: "Pending Review",
    completed: "Completed",
    myEvidence: "My Evidence",
    assignedCasesTab: "Assigned Cases",
    fieldNotes: "Field Notes",
    uploadEvidence2: "UPLOAD EVIDENCE",
    verifyEvidence2: "VERIFY EVIDENCE",
    searchAssignedCases: "Search assigned cases...",
    writeFieldNote: "Write your field note...",
    saveNote: "SAVE NOTE",
    assigned: "ASSIGNED",
    // Citizen Portal
    citizenComplaintPortal: "CITIZEN COMPLAINT PORTAL",
    publicAccess: "PUBLIC ACCESS",
    submitTrackVerify: "Submit · Track · Verify",
    fileComplaint: "File Complaint",
    caseAssigned: "Case Assigned",
    investigation: "Investigation",
    resolution: "Resolution",
    fileComplaintTab: "File Complaint",
    trackCase: "Track Case",
    verifyEvidenceTab: "Verify Evidence",
    fullName: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    contactEmail: "Contact / Email",
    contactPlaceholder: "Enter your email or phone",
    incidentDate: "Incident Date",
    scamTypeLabel: "Scam Type",
    incidentDescription: "Incident Description",
    incidentDescPlaceholder: "Describe the incident in detail...",
    submitComplaint: "SUBMIT COMPLAINT",
    evidenceTip: "To attach evidence files, use the Evidence Upload page.",
    complaintSuccess: "Complaint Filed Successfully",
    complaintSuccessDesc:
      "Your complaint has been registered. You will receive a Case ID within 24 hours.",
    fileAnother: "File Another",
    enterCaseId: "ENTER CASE ID",
    caseIdPlaceholder: "e.g. DEPS-2024-0047",
    track: "TRACK",
    underInvestigation: "UNDER INVESTIGATION",
    lastUpdated: "Last Updated",
    assignedOfficerLabel: "Assigned Officer",
    departmentLabel: "Department",
    cyberCrimeUnit: "Cyber Crime Unit",
    goToVerification: "GO TO VERIFICATION PAGE",
    evidenceVerificationDesc:
      "Use the Evidence Verification module to verify the SHA-256 hash of any uploaded file. This ensures the file has not been tampered with since it was submitted.",
    // Admin Panel
    adminPanel: "Admin Panel",
    adminOverview: "System Overview",
    adminRecords: "Case Records",
    adminGraphs: "Analytics & Graphs",
    totalCases: "Total Cases",
    activeCasesCount: "Active Cases",
    pendingCasesCount: "Pending Cases",
    resolvedCases: "Resolved Cases",
    caseRecordId: "Record ID",
    caseRecordTitle: "Case Title",
    caseRecordStatus: "Status",
    caseRecordType: "Type",
    caseRecordDate: "Date Filed",
    caseRecordOfficer: "Assigned Officer",
    statusPending: "Pending",
    statusInProgress: "In Progress",
    statusUnderReview: "Under Review",
    statusClosed: "Closed",
    statusVerified: "Verified",
    evidenceByType: "Evidence by Scam Type",
    caseStatusDist: "Case Status Distribution",
    uploadTrend: "7-Day Upload Trend",
  },
  hi: {
    appName: "डिजिटल साक्ष्य संरक्षण प्रणाली",
    appShort: "DEPS",
    home: "होम",
    about: "सिस्टम के बारे में",
    upload: "साक्ष्य अपलोड",
    verify: "साक्ष्य सत्यापित करें",
    dashboard: "केस डैशबोर्ड",
    admin: "एडमिन पैनल",
    contact: "संपर्क",
    login: "लॉगिन",
    logout: "लॉगआउट",
    signup: "साइन अप",
    uploadEvidence: "साक्ष्य अपलोड करें",
    verifyEvidence: "साक्ष्य सत्यापित करें",
    evidenceId: "साक्ष्य आईडी",
    sha256Hash: "SHA-256 हैश",
    tamperDetected: "छेड़छाड़ पाई गई",
    evidenceVerified: "साक्ष्य सत्यापित",
    uploadFile: "फ़ाइल अपलोड करें",
    createCase: "केस बनाएं",
    activityLog: "गतिविधि लॉग",
    caseId: "केस आईडी",
    status: "स्थिति",
    description: "विवरण",
    fileName: "फ़ाइल नाम",
    fileSize: "फ़ाइल आकार",
    fileType: "फ़ाइल प्रकार",
    timestamp: "समय चिह्न",
    uploadedBy: "द्वारा अपलोड",
    sealCase: "केस सील करें",
    assignEvidence: "साक्ष्य असाइन करें",
    noTampering: "साक्ष्य सत्यापित — कोई छेड़छाड़ नहीं",
    tamperAlert: "छेड़छाड़ पाई गई — हैश मेल नहीं खाता",
    heroSubtitle:
      "कानून प्रवर्तन, फोरेंसिक टीमों और न्यायिक अधिकारियों के लिए क्रिप्टोग्राफिक अखंडता के साथ डिजिटल साक्ष्य सुरक्षित करना।",
    getStarted: "शुरू करें",
    learnMore: "अधिक जानें",
    secureStorage: "छेड़छाड़-रोधी भंडारण",
    hashIntegrity: "SHA-256 अखंडता",
    roleAccess: "भूमिका-आधारित पहुँच",
    chainCustody: "हिरासत की श्रृंखला",
    realTimeVerify: "वास्तविक-समय सत्यापन",
    multiAgency: "बहु-एजेंसी समर्थन",
    evidenceSecured: "सुरक्षित साक्ष्य",
    casesSolved: "हल किए गए मामले",
    agencies: "एजेंसियाँ",
    uptime: "अपटाइम",
    name: "नाम",
    email: "ईमेल",
    message: "संदेश",
    send: "संदेश भेजें",
    department: "विभाग",
    badgeNumber: "बैज नंबर",
    role: "भूमिका",
    displayName: "प्रदर्शन नाम",
    password: "पासवर्ड",
    allCases: "सभी मामले",
    openCases: "खुले मामले",
    totalEvidence: "कुल साक्ष्य",
    recentActivity: "हालिया गतिविधि",
    users: "उपयोगकर्ता",
    cases: "मामले",
    evidence: "साक्ष्य",
    logs: "लॉग",
    officers: "अधिकारी",
    investigators: "जाँचकर्ता",
    admins: "व्यवस्थापक",
    howItWorks: "यह कैसे काम करता है",
    step1: "साक्ष्य अपलोड करें",
    step1Desc: "मेटाडेटा और केस विवरण के साथ डिजिटल फ़ाइलें सुरक्षित रूप से अपलोड करें।",
    step2: "हैश और रिकॉर्ड",
    step2Desc:
      "SHA-256 हैश की गणना की जाती है और ब्लॉकचेन पर अपरिवर्तनीय रूप से संग्रहीत किया जाता है।",
    step3: "अखंडता सत्यापित करें",
    step3Desc: "छेड़छाड़ या भ्रष्टाचार का पता लगाने के लिए कभी भी हैश की तुलना करें।",
    // About page
    aboutTagline: "सिस्टम के बारे में",
    aboutHeroTitle: "डिजिटल सच्चाई की",
    aboutHeroTitleHighlight: "सुरक्षा",
    aboutHeroDesc:
      "DEPS एक अगली पीढ़ी का फोरेंसिक साक्ष्य प्रबंधन प्लेटफ़ॉर्म है जो क्रिप्टोग्राफिक सिद्धांतों और विकेंद्रीकृत बुनियादी ढांचे पर बनाया गया है। हमारा मिशन: यह सुनिश्चित करना कि डिजिटल साक्ष्य का हर टुकड़ा प्रामाणिक, सत्यापन योग्य और कानूनी रूप से स्वीकार्य रहे।",
    ourMission: "हमारा",
    ourMissionHighlight: "मिशन",
    missionDesc1:
      "ऐसे युग में जहाँ डिजिटल साक्ष्य न्याय के लिए केंद्रीय है, छेड़छाड़ और हेरफेर कानूनी कार्यवाही के लिए गंभीर खतरे पैदा करते हैं। DEPS इस समस्या को निश्चित रूप से हल करने के लिए बनाया गया था।",
    missionDesc2:
      "SHA-256 क्रिप्टोग्राफिक हैशिंग को ब्लॉकचेन अपरिवर्तनीयता के साथ मिलाकर, हम एक ऐसी प्रणाली बनाते हैं जहाँ साक्ष्य की अखंडता को गणितीय रूप से सिद्ध किया जा सकता है — केवल दावा नहीं।",
    systemStats: "सिस्टम आँकड़े",
    statEvidenceRecords: "कुल साक्ष्य रिकॉर्ड",
    statHashVerifications: "किए गए हैश सत्यापन",
    statTamperAttempts: "पाई गई छेड़छाड़ की कोशिशें",
    statActiveAgencies: "सक्रिय एजेंसियाँ",
    statSystemUptime: "सिस्टम अपटाइम",
    techStack: "तकनीकी",
    techStackHighlight: "स्टैक",
    whoUses: "कौन उपयोग करता है",
    techIcpTitle: "ICP ब्लॉकचेन",
    techIcpDesc:
      "साक्ष्य मेटाडेटा और हैश इंटरनेट कंप्यूटर प्रोटोकॉल पर स्थायी रूप से संग्रहीत — एक विकेंद्रीकृत, छेड़छाड़-रोधी ब्लॉकचेन प्लेटफ़ॉर्म।",
    techShaTitle: "SHA-256 क्रिप्टोग्राफिक हैशिंग",
    techShaDesc:
      "उद्योग-मानक एकतरफा हैश फ़ंक्शन प्रत्येक फ़ाइल के लिए एक अद्वितीय 256-बिट फिंगरप्रिंट उत्पन्न करता है। किसी भी बाइट-स्तरीय परिवर्तन से पूरी तरह अलग हैश बनता है।",
    techRbacTitle: "भूमिका-आधारित पहुँच नियंत्रण",
    techRbacDesc:
      "तीन-स्तरीय अनुमति प्रणाली (एडमिन, जाँचकर्ता, अधिकारी) यह सुनिश्चित करती है कि केवल अधिकृत कर्मी ही साक्ष्य अपलोड, देख या प्रबंधित कर सकते हैं।",
    techStorageTitle: "विकेंद्रीकृत भंडारण",
    techStorageDesc:
      "फ़ाइलें ExternalBlob संदर्भों का उपयोग करके वितरित तरीके से संग्रहीत की जाती हैं — विफलता या सेंसरशिप का कोई एकल बिंदु नहीं।",
    useLawTitle: "कानून प्रवर्तन",
    useLawDesc:
      "पुलिस एजेंसियाँ स्वचालित हिरासत-की-श्रृंखला लॉगिंग के साथ अपराध स्थल के डिजिटल साक्ष्य अपलोड कर सकती हैं, जिससे अदालत में स्वीकार्यता सुनिश्चित होती है।",
    useForensicsTitle: "साइबर फोरेंसिक्स",
    useForensicsDesc:
      "फोरेंसिक विश्लेषक क्रिप्टोग्राफिक अखंडता गारंटी के साथ डिस्क इमेज, मेमोरी डंप और नेटवर्क कैप्चर सुरक्षित कर सकते हैं।",
    useJudiciaryTitle: "न्यायपालिका",
    useJudiciaryDesc:
      "अदालतें सार्वजनिक सत्यापन मॉड्यूल का उपयोग करके कार्यवाही से पहले स्वतंत्र रूप से साक्ष्य की अखंडता सत्यापित कर सकती हैं।",
    // Scam types
    scamType: "स्कैम प्रकार",
    selectScamType: "स्कैम प्रकार चुनें",
    phishing: "फिशिंग अटैक",
    financialFraud: "वित्तीय धोखाधड़ी",
    identityTheft: "पहचान चोरी",
    shoppingScam: "ऑनलाइन शॉपिंग स्कैम",
    investmentScam: "निवेश धोखाधड़ी",
    jobFraud: "नौकरी धोखाधड़ी",
    lotteryScam: "लॉटरी/इनाम स्कैम",
    romanceScam: "रोमांस स्कैम",
    cyberBullying: "साइबर बुलिंग",
    ransomware: "रैनसमवेयर/मैलवेयर",
    // Role Portal
    myPortal: "मेरा पोर्टल",
    selectRole: "अपनी भूमिका चुनें",
    selectRoleDesc: "अपने व्यक्तिगत डैशबोर्ड तक पहुँचने के लिए अपनी भूमिका चुनें",
    investigatorRole: "जाँचकर्ता",
    investigatorRoleDesc: "केस फाइलें, साक्ष्य समीक्षा और अभिरक्षा श्रृंखला तक पहुँच",
    officerRole: "फील्ड अधिकारी",
    officerRoleDesc: "साक्ष्य जमा करें, असाइनमेंट प्रबंधित करें और फील्ड नोट्स",
    citizenRole: "नागरिक",
    citizenRoleDesc: "शिकायत दर्ज करें, केस ट्रैक करें और साक्ष्य सत्यापित करें",
    enterDashboard: "डैशबोर्ड में प्रवेश करें",
    // Investigator Dashboard
    investigatorPortal: "जाँचकर्ता पोर्टल",
    restrictedAccess: "प्रतिबंधित पहुँच",
    activeCases: "सक्रिय मामले",
    evidenceItems: "साक्ष्य आइटम",
    pendingReview: "समीक्षा लंबित",
    chainEntries: "चेन प्रविष्टियाँ",
    caseFiles: "केस फाइलें",
    evidenceReview: "साक्ष्य समीक्षा",
    chainOfCustody: "अभिरक्षा श्रृंखला",
    analytics: "विश्लेषण",
    searchCases: "केस खोजें...",
    searchEvidence: "साक्ष्य खोजें...",
    caseIdLabel: "केस आईडी",
    priorityLabel: "प्राथमिकता",
    evidenceCount: "साक्ष्य संख्या",
    high: "उच्च",
    medium: "मध्यम",
    low: "निम्न",
    verified: "सत्यापित",
    pending: "लंबित",
    active: "सक्रिय",
    closed: "बंद",
    open: "खुला",
    // Officer Dashboard
    officerFieldPortal: "अधिकारी फील्ड पोर्टल",
    fieldAccess: "फील्ड पहुँच",
    activeDuty: "सक्रिय ड्यूटी",
    mySubmissions: "मेरे सबमिशन",
    assignedCases: "असाइन किए गए मामले",
    pendingReviewStat: "समीक्षा लंबित",
    completed: "पूर्ण",
    myEvidence: "मेरे साक्ष्य",
    assignedCasesTab: "असाइन किए गए मामले",
    fieldNotes: "फील्ड नोट्स",
    uploadEvidence2: "साक्ष्य अपलोड करें",
    verifyEvidence2: "साक्ष्य सत्यापित करें",
    searchAssignedCases: "असाइन किए गए केस खोजें...",
    writeFieldNote: "फील्ड नोट लिखें...",
    saveNote: "नोट सहेजें",
    assigned: "असाइन किया",
    // Citizen Portal
    citizenComplaintPortal: "नागरिक शिकायत पोर्टल",
    publicAccess: "सार्वजनिक पहुँच",
    submitTrackVerify: "जमा करें · ट्रैक करें · सत्यापित करें",
    fileComplaint: "शिकायत दर्ज करें",
    caseAssigned: "केस असाइन हुआ",
    investigation: "जाँच",
    resolution: "समाधान",
    fileComplaintTab: "शिकायत दर्ज करें",
    trackCase: "केस ट्रैक करें",
    verifyEvidenceTab: "साक्ष्य सत्यापित करें",
    fullName: "पूरा नाम",
    fullNamePlaceholder: "अपना पूरा नाम दर्ज करें",
    contactEmail: "संपर्क / ईमेल",
    contactPlaceholder: "अपना ईमेल या फोन दर्ज करें",
    incidentDate: "घटना की तारीख",
    scamTypeLabel: "स्कैम प्रकार",
    incidentDescription: "घटना विवरण",
    incidentDescPlaceholder: "घटना का विस्तार से वर्णन करें...",
    submitComplaint: "शिकायत जमा करें",
    evidenceTip: "साक्ष्य फाइलें संलग्न करने के लिए, साक्ष्य अपलोड पेज का उपयोग करें।",
    complaintSuccess: "शिकायत सफलतापूर्वक दर्ज हुई",
    complaintSuccessDesc:
      "आपकी शिकायत दर्ज की जा चुकी है। आपको 24 घंटे में केस आईडी मिलेगी।",
    fileAnother: "दूसरी शिकायत दर्ज करें",
    enterCaseId: "केस आईडी दर्ज करें",
    caseIdPlaceholder: "जैसे DEPS-2024-0047",
    track: "ट्रैक करें",
    underInvestigation: "जाँच जारी",
    lastUpdated: "अंतिम अपडेट",
    assignedOfficerLabel: "असाइन किया गया अधिकारी",
    departmentLabel: "विभाग",
    cyberCrimeUnit: "साइबर अपराध इकाई",
    goToVerification: "सत्यापन पेज पर जाएं",
    evidenceVerificationDesc:
      "अपलोड की गई फाइल का SHA-256 हैश सत्यापित करने के लिए साक्ष्य सत्यापन मॉड्यूल का उपयोग करें। यह सुनिश्चित करता है कि फाइल जमा होने के बाद से छेड़छाड़ नहीं हुई।",
    // Admin Panel
    adminPanel: "एडमिन पैनल",
    adminOverview: "सिस्टम सारांश",
    adminRecords: "केस रिकॉर्ड",
    adminGraphs: "विश्लेषण और ग्राफ",
    totalCases: "कुल मामले",
    activeCasesCount: "सक्रिय मामले",
    pendingCasesCount: "लंबित मामले",
    resolvedCases: "हल किए गए मामले",
    caseRecordId: "रिकॉर्ड आईडी",
    caseRecordTitle: "केस शीर्षक",
    caseRecordStatus: "स्थिति",
    caseRecordType: "प्रकार",
    caseRecordDate: "दर्ज तारीख",
    caseRecordOfficer: "असाइन अधिकारी",
    statusPending: "लंबित",
    statusInProgress: "प्रगति में",
    statusUnderReview: "समीक्षाधीन",
    statusClosed: "बंद",
    statusVerified: "सत्यापित",
    evidenceByType: "स्कैम प्रकार अनुसार साक्ष्य",
    caseStatusDist: "केस स्थिति वितरण",
    uploadTrend: "7-दिन अपलोड ट्रेंड",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  const t = (key: TranslationKey): string => translations[lang][key] as string;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
