/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EvidenceId = IDL.Nat;
export const CaseId = IDL.Nat;
export const CaseStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const Time = IDL.Int;
export const CaseRecord = IDL.Record({
  'status' : CaseStatus,
  'title' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'caseId' : CaseId,
  'assignedOfficer' : IDL.Opt(IDL.Principal),
  'evidenceIds' : IDL.Vec(EvidenceId),
});
export const EvidenceStatus = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EvidenceRecord = IDL.Record({
  'status' : EvidenceStatus,
  'sha256Hash' : IDL.Text,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'timestamp' : Time,
  'caseId' : IDL.Opt(CaseId),
  'evidenceId' : EvidenceId,
  'uploadedBy' : IDL.Principal,
  'fileReference' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'investigator' : IDL.Null,
  'officer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
  'role' : UserRole,
  'department' : IDL.Text,
  'badgeNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignEvidenceToCase' : IDL.Func([EvidenceId, CaseId], [], []),
  'createCase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
      [CaseId],
      [],
    ),
  'getAllCases' : IDL.Func([], [IDL.Vec(CaseRecord)], ['query']),
  'getAllEvidence' : IDL.Func([], [IDL.Vec(EvidenceRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCase' : IDL.Func([CaseId], [CaseRecord], ['query']),
  'getCasesByOfficer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CaseRecord)],
      ['query'],
    ),
  'getEvidence' : IDL.Func([EvidenceId], [EvidenceRecord], ['query']),
  'getEvidenceByCase' : IDL.Func(
      [CaseId],
      [IDL.Vec(EvidenceRecord)],
      ['query'],
    ),
  'getEvidenceByUploader' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EvidenceRecord)],
      ['query'],
    ),
  'getMyCases' : IDL.Func([], [IDL.Vec(CaseRecord)], ['query']),
  'getMyEvidence' : IDL.Func([], [IDL.Vec(EvidenceRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sealCase' : IDL.Func([CaseId], [], []),
  'searchEvidence' : IDL.Func([IDL.Text], [IDL.Vec(EvidenceRecord)], ['query']),
  'uploadEvidence' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, ExternalBlob],
      [EvidenceId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EvidenceId = IDL.Nat;
  const CaseId = IDL.Nat;
  const CaseStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const Time = IDL.Int;
  const CaseRecord = IDL.Record({
    'status' : CaseStatus,
    'title' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'caseId' : CaseId,
    'assignedOfficer' : IDL.Opt(IDL.Principal),
    'evidenceIds' : IDL.Vec(EvidenceId),
  });
  const EvidenceStatus = IDL.Variant({
    'active' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EvidenceRecord = IDL.Record({
    'status' : EvidenceStatus,
    'sha256Hash' : IDL.Text,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'timestamp' : Time,
    'caseId' : IDL.Opt(CaseId),
    'evidenceId' : EvidenceId,
    'uploadedBy' : IDL.Principal,
    'fileReference' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'investigator' : IDL.Null,
    'officer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
    'role' : UserRole,
    'department' : IDL.Text,
    'badgeNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignEvidenceToCase' : IDL.Func([EvidenceId, CaseId], [], []),
    'createCase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Principal)],
        [CaseId],
        [],
      ),
    'getAllCases' : IDL.Func([], [IDL.Vec(CaseRecord)], ['query']),
    'getAllEvidence' : IDL.Func([], [IDL.Vec(EvidenceRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCase' : IDL.Func([CaseId], [CaseRecord], ['query']),
    'getCasesByOfficer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CaseRecord)],
        ['query'],
      ),
    'getEvidence' : IDL.Func([EvidenceId], [EvidenceRecord], ['query']),
    'getEvidenceByCase' : IDL.Func(
        [CaseId],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'getEvidenceByUploader' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'getMyCases' : IDL.Func([], [IDL.Vec(CaseRecord)], ['query']),
    'getMyEvidence' : IDL.Func([], [IDL.Vec(EvidenceRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sealCase' : IDL.Func([CaseId], [], []),
    'searchEvidence' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EvidenceRecord)],
        ['query'],
      ),
    'uploadEvidence' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text, ExternalBlob],
        [EvidenceId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };