/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CaseId = bigint;
export interface CaseRecord {
  'status' : CaseStatus,
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'caseId' : CaseId,
  'assignedOfficer' : [] | [Principal],
  'evidenceIds' : Array<EvidenceId>,
}
export type CaseStatus = { 'closed' : null } |
  { 'open' : null };
export type EvidenceId = bigint;
export interface EvidenceRecord {
  'status' : EvidenceStatus,
  'sha256Hash' : string,
  'description' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : string,
  'timestamp' : Time,
  'caseId' : [] | [CaseId],
  'evidenceId' : EvidenceId,
  'uploadedBy' : Principal,
  'fileReference' : ExternalBlob,
}
export type EvidenceStatus = { 'active' : null } |
  { 'archived' : null };
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserProfile {
  'displayName' : string,
  'userId' : Principal,
  'role' : UserRole,
  'department' : string,
  'badgeNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'investigator' : null } |
  { 'officer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignEvidenceToCase' : ActorMethod<[EvidenceId, CaseId], undefined>,
  'createCase' : ActorMethod<[string, string, [] | [Principal]], CaseId>,
  'getAllCases' : ActorMethod<[], Array<CaseRecord>>,
  'getAllEvidence' : ActorMethod<[], Array<EvidenceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCase' : ActorMethod<[CaseId], CaseRecord>,
  'getCasesByOfficer' : ActorMethod<[Principal], Array<CaseRecord>>,
  'getEvidence' : ActorMethod<[EvidenceId], EvidenceRecord>,
  'getEvidenceByCase' : ActorMethod<[CaseId], Array<EvidenceRecord>>,
  'getEvidenceByUploader' : ActorMethod<[Principal], Array<EvidenceRecord>>,
  'getMyCases' : ActorMethod<[], Array<CaseRecord>>,
  'getMyEvidence' : ActorMethod<[], Array<EvidenceRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sealCase' : ActorMethod<[CaseId], undefined>,
  'searchEvidence' : ActorMethod<[string], Array<EvidenceRecord>>,
  'uploadEvidence' : ActorMethod<
    [string, string, bigint, string, string, ExternalBlob],
    EvidenceId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];